#!/bin/sh

stop_zookeeper()
{
	echo 'stop zookeeper'
	# for id in `ps -ef | grep 'zookeeper' | grep -v grep | awk '{print $2}'`; do kill $id; done;
	~/component/zookeeper-3.4.12/bin/zkServer.sh stop
	echo 'stop zookeeper success. \n'
}

stop_redis()
{
	echo 'stop redis'
	~/component/shell/redis.sh stop
	echo 'stop redis success. \n'
}


stop_rocketmq()
{
	echo 'stop rocketmq'
	sh ~/component/rocketmq/bin/mqshutdown broker
	sh ~/component/rocketmq/bin/mqshutdown namesrv
	echo 'stop rocketmq success. \n'

	echo 'stop rocketmq-console'
	#for id in `ps -ef | grep 'rocketmq' | grep -v grep | awk '{print $2}'`; do kill -9 $id; done;
  ps -ef | grep 'rocketmq' | grep -v grep | awk '{print $2}' |xargs kill -9
	echo 'stop rocketmq-console success.\n'
}

stop_kafka()
{
	echo 'stop kafka'
	sh ~/component/kafka_2.12-2.2.0/bin/kafka-server-stop.sh
	echo 'stop kafka success. \n'
}

stop_tomcat()
{
	echo 'stop tomcat'
	nohup sh ~/component/apache-tomcat-9.0.27/bin/shutdown.sh  >/dev/null 2>&1 &
	echo 'stop tomcat success. \n'
}

stop_rabbitmq()
{
	echo 'stop rabbitmq'
	brew services stop rabbitmq
	echo 'stop rabbitmq success. \n'
}

stop_mongodb()
{
  echo 'stop mongodb'
  brew services stop mongodb-community
  echo 'stop mongodb success. \n'
}

stop_elasticsearch()
{
  echo 'stop elasticsearch'
  pkill -F 100
  echo 'stop elasticsearch success. \n'
}

stop_nacos()
{
  echo 'stop nacos'
  ~/project/java/nacos/distribution/target/nacos-server-2.0.3/nacos/bin/shutdown.sh
  echo 'stop nacos success. \n'
}

stop_nginx() 
{
  sudo nginx -s stop
}

case "$1" in
  zookeeper)
        stop_zookeeper
        ;;
  redis)
        stop_redis
        ;;
  rocketmq)
        stop_rocketmq
        ;;
  kafka)
        stop_kafka
        ;;
  tomcat)
        stop_tomcat
        ;;
  rabbitmq)
        stop_rabbitmq
        ;;
  mongodb)
        stop_mongodb
        ;;
  elasticsearch)
        stop_elasticsearch
        ;;
  nacos)
        stop_nacos
        ;;
  nginx)
        stop_nginx
        ;;
  all)
        stop_zookeeper
        stop_redis
        stop_rocketmq
        stop_kafka
        stop_tomcat
        stop_rabbitmq
        stop_nginx
        ;;
  *)
        echo $"Usage: $0 {zookeeper|redis|rocketmq|kafka|tomcat|rabbitmq|mongodb|elasticsearch|nginx|all}"
        exit 1
esac
exit 0
